# Generated by Django 6.0 on 2026-01-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilotprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
        migrations.DeleteModel(
            name='PilotProfile',
        ),
    ]
