# Generated by Django 6.0 on 2025-12-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('left_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='identity',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='identity/'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
