# Generated by Django 6.0 on 2025-12-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('left_panel', '0002_identity_user_alter_identity_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='profile_picture',
            field=models.ImageField(blank=True, default='image/default_pilot_pfp.jpg', null=True, upload_to='identity/'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='status',
            field=models.CharField(blank=True, default='No Status Yet', max_length=255),
        ),
    ]
