# Generated by Django 6.0 on 2026-01-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('left_panel', '0003_alter_identity_profile_picture_alter_identity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='identity',
            name='about_heading',
            field=models.CharField(blank=True, default='Welcome', max_length=50),
        ),
    ]
